language: cpp
matrix:
  include:
    - os: osx
      compiler: clang
      env: STRUS_WITH_PYTHON=YES STRUS_WITH_PHP=NO STRUS_WITH_LUA=NO
    - os: osx
      compiler: clang
      env: STRUS_WITH_PYTHON=NO STRUS_WITH_PHP=NO STRUS_WITH_LUA=YES
    - os: linux
      dist: trusty
      compiler: clang
      env: STRUS_WITH_PYTHON=YES STRUS_WITH_PHP=NO STRUS_WITH_LUA=NO
    - os: linux
      dist: trusty
      compiler: clang
      env: STRUS_WITH_PYTHON=NO STRUS_WITH_PHP=YES STRUS_WITH_LUA=NO
    - os: linux
      dist: trusty
      compiler: clang
      env: STRUS_WITH_PYTHON=NO STRUS_WITH_PHP=NO STRUS_WITH_LUA=YES
    - os: linux
      dist: trusty
      compiler: gcc
      env: STRUS_WITH_PYTHON=YES STRUS_WITH_PHP=NO STRUS_WITH_LUA=NO
    - os: linux
      dist: trusty
      compiler: gcc
      env: STRUS_WITH_PYTHON=NO STRUS_WITH_PHP=YES STRUS_WITH_LUA=NO
    - os: linux
      dist: trusty
      compiler: gcc
      env: STRUS_WITH_PYTHON=NO STRUS_WITH_PHP=NO STRUS_WITH_LUA=YES

sudo: required
branches:
  only:
    - master
before_install:
- chmod +x dist/travis/*.sh
- dist/travis/before_script.sh
script:
- dist/travis/script.sh
