TOPDIR=..
include $(TOPDIR)/variables.mk

SWIG=swig2.0 -Wall -Wallkw -Werror -I. -c++ -small -outdir gen

all: gen php java ruby csharp perl python tcl ocaml xml

-include php.d
-include java.d
-include ruby.d
-include csharp.d
-include perl.d
-include python.d
-include tcl.d
-include ocaml.d
-include xml.d

gen:
	mkdir -p gen

php: php.d
	$(SWIG) -php strus.i

php.d:
	$(SWIG) -MM -php strus.i > php.d

java: java.d
	$(SWIG) -java strus.i

java.d:
	$(SWIG) -MM -java strus.i > java.d

ruby: ruby.d
	$(SWIG) -ruby strus.i

ruby.d:
	$(SWIG) -MM -ruby strus.i > ruby.d

csharp: csharp.d
	$(SWIG) -csharp strus.i

csharp.d:
	$(SWIG) -MM -csharp strus.i > csharp.d

perl: perl.d
	$(SWIG) -perl strus.i

perl.d:
	$(SWIG) -MM -perl strus.i > perl.d

python: python.d
	$(SWIG) -python strus.i

python.d:
	$(SWIG) -MM -python strus.i > python.d

tcl: tcl.d
	$(SWIG) -tcl strus.i

tcl.d:
	$(SWIG) -MM -tcl strus.i > tcl.d

ocaml:
	$(SWIG) -ocaml strus.i

ocaml.d:
	$(SWIG) -MM -ocaml strus.i > ocaml.d

xml:
	$(SWIG) -xml strus.i

xml.d:
	$(SWIG) -MM -ocaml strus.i > xml.d

test: all

clean:
	@-rm -f gen/*
	@-rm -f *.d
	@-rmdir gen
	@-rm -f strus_wrap.cpp
	@-rm -f strus_wrap.cxx
	@-rm -f strus_wrap.xml

install:

uninstall:


