{
"statserver":{
"types":[
	"cithead",
	"entity",
	"title",
	"word"],
"nofdocs": 18}}
{
"statistics":{
"termstats":[
	{
		"type": "word",
		"value": "iggy",
		"df": 5},
	{
		"type": "word",
		"value": "pop",
		"df": 10},
	{
		"type": "entity",
		"value": "iggy_pop",
		"df": 5}],
"globalstats":{
	"nofdocs": 18}}}
{
"list":{
"link":[
	"storage",
	"statserver"]}}
{
"distqryeval": {
  "qryeval": [
    "http://127.0.0.1:7184/storage/test1",
    "http://127.0.0.1:7185/storage/test2",
    "http://127.0.0.1:7186/storage/test3"],
  "statserver": "http://127.0.0.1:7183/statserver/test"}}
{
"queryresult":{
"ranklist":{
	"evalpass": 0,
	"nofranked": 10,
	"nofvisited": 10,
	"ranks":[
		{
			"weight": "1.207559",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "Tonight (David Bowie album)"}]},
		{
			"weight": "0.989673",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "VH1 Storytellers (David Bowie album)"}]},
		{
			"weight": "0.922050",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "List of songs recorded by David Bowie"}]},
		{
			"weight": "0.482583",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "Let's Dance (David Bowie album)"}]},
		{
			"weight": "0.436904",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "David Bowie"}]},
		{
			"weight": "0.000016",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "Liza Jane (David Bowie song)"}]},
		{
			"weight": "0.000010",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "List of awards and nominations received by David Bowie"}]},
		{
			"weight": "0.000007",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "David Bowie (1967 album)"}]},
		{
			"weight": "0.000006",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "Stage (David Bowie album)"}]},
		{
			"weight": "0.000003",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "Outside (David Bowie album)"}]}]}}}
{
"queryresult":{
"ranklist":{
	"evalpass": 0,
	"nofranked": 5,
	"nofvisited": 5,
	"ranks":[
		{
			"weight": "0.417467",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "Liza Jane (David Bowie song)"}]},
		{
			"weight": "0.262937",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "Never Let Me Down (David Bowie song)"}]},
		{
			"weight": "0.258236",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "David Bowie (1967 album)"}]},
		{
			"weight": "0.122097",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "List of songs recorded by David Bowie"}]},
		{
			"weight": "0.113393",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "David Bowie"}]}]}}}
