{
"statserver": {
	"types": ["entity","title","word"],
	"nofdocs": 18}
}

{
"statserver": {
	"types": ["entity","title","word"],
	"nofdocs": 18}
}

{
"statistics": {
	"termstats": [
		{
			"type": "word",
			"value": "iggy",
			"df": 5},
		{
			"type": "word",
			"value": "pop",
			"df": 10},
		{
			"type": "entity",
			"value": "iggy_pop",
			"df": 5}],
	"globalstats": {
		"nofdocs": 18}}
}

{
"list": {
	"link": ["storage","statserver"]}
}

{ 
"distqryeval": { 
  "statserver": "http://127.0.0.1:7183/statserver/test",
  "storage": [ 
    "http://127.0.0.1:7184/storage/test",
    "http://127.0.0.1:7185/storage/test",
    "http://127.0.0.1:7186/storage/test" ] } }

