{
"qryanalyzer": {
	"element": [
		{
			"field": "text",
			"normalizer": [
				{
					"name": "lc"}],
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"field": "text",
			"normalizer": [
				{
					"name": "entityid"},
				{
					"name": "lc"}],
			"tokenizer": {
				"name": "content"},
			"type": "entity"}]}
}

{
"query": {
	"feature": [
		{
			"content": [
				{
					"type": "text",
					"value": "Iggy Pop"}],
			"analyzed": [
				{
					"term": {
						"type": "word",
						"value": "iggy"}},
				{
					"term": {
						"type": "word",
						"value": "pop"}},
				{
					"term": {
						"type": "entity",
						"value": "iggy_pop"}}],
			"set": "search"}]}
}

{
"query": {
	"feature": [
		{
			"content": [
				{
					"type": "text",
					"value": "Iggy Pop"}],
			"analyzed": [
				{
					"term": {
						"type": "word",
						"value": "IGGY"}},
				{
					"term": {
						"type": "word",
						"value": "POP"}}],
			"set": "search"}]}
}

