{
"qryanalyzer": {
	"element": [
		{
			"field": "text",
			"normalizer": [
				{
					"name": "lc"}],
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"field": "text",
			"normalizer": [
				{
					"name": "entityid"},
				{
					"name": "lc"}],
			"tokenizer": {
				"name": "content"},
			"type": "entity"}]}
}
{
"query": {
	"feature": [
		{
			"content": [
				{
					"type": "text",
					"value": "Iggy Pop"}],
			"analyzed": [
				{
					"type": "word",
					"value": "iggy"},
				{
					"type": "word",
					"value": "pop"},
				{
					"type": "entity",
					"value": "iggy_pop"}],
			"set": "search"}]}
}
{
"query": {
	"feature": [
		{
			"content": [
				{
					"type": "text",
					"value": "Iggy Pop"}],
			"analyzed": [
				{
					"type": "word",
					"value": "IGGY"},
				{
					"type": "word",
					"value": "POP"}],
			"set": "search"}]}
}
