{
"qryanalyzer": {
  "element": [
    {
      "field": "text",
      "normalizer": [
        {
          "name": "lc"}],
      "tokenizer": {
        "name": "word"},
      "type": "word"},
    {
      "field": "text",
      "normalizer": [
        {
          "name": "entityid"},
        {
          "name": "lc"}],
      "tokenizer": {
        "name": "content"},
      "type": "entity"}]}}
{
"query": {
  "feature": [
    {
      "analyzed": [
        {
          "term": {
            "type": "word",
            "value": "iggy"}},
        {
          "term": {
            "type": "word",
            "value": "pop"}},
        {
          "term": {
            "type": "entity",
            "value": "iggy_pop"}}],
      "content": {
        "type": "text",
        "value": "Iggy Pop"},
      "set": "search"}]}}
