{
"analyzer": {
	"element": [
		{
			"field": "text",
			"normalizer": [
				{
					"name": "lc"}],
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"field": "text",
			"normalizer": [
				{
					"name": "entityid"},
				{
					"name": "lc"}],
			"tokenizer": {
				"name": "content"},
			"type": "entity"}]}
}
{
"analyzer": {
	"aggregator": [
		{
			"function": {
				"name": "count",
				"types": ["word"]},
			"type": "doclen"}],
	"attribute": [
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "/doc/title()",
			"tokenizer": {
				"name": "content"},
			"type": "title"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "/doc/docid()",
			"tokenizer": {
				"name": "content"},
			"type": "docid"}],
	"forwardindex": [
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//weblink@id",
			"tokenizer": {
				"expression": "^[a-z]{3,6}[:][/][/]([^ ?]*)",
				"index": 0,
				"name": "regex"},
			"type": "url"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//weblink@id",
			"tokenizer": {
				"expression": "^([a-z]{1,32}[.][^ ?]*)",
				"index": 0,
				"name": "regex"},
			"type": "url"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//pagelink@id",
			"tokenizer": {
				"name": "content"},
			"type": "pageref"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//bibref()",
			"tokenizer": {
				"name": "content"},
			"type": "bibref"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//time()",
			"tokenizer": {
				"name": "content"},
			"type": "time"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//category@cid",
			"tokenizer": {
				"name": "content"},
			"type": "categoryid"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//title@id",
			"tokenizer": {
				"name": "content"},
			"type": "headingid"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//heading@id",
			"tokenizer": {
				"name": "content"},
			"type": "headingid"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//N@id",
			"tokenizer": {
				"name": "content"},
			"type": "entityref"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//E@id",
			"tokenizer": {
				"name": "content"},
			"type": "entityref"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//R@id",
			"tokenizer": {
				"name": "content"},
			"type": "entityref"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//T()",
			"tokenizer": {
				"name": "content"},
			"type": "punct"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//P()",
			"tokenizer": {
				"name": "content"},
			"type": "comma"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//C()",
			"tokenizer": {
				"name": "content"},
			"type": "cardinal"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//X()",
			"tokenizer": {
				"name": "content"},
			"type": "exist"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//A()",
			"tokenizer": {
				"name": "content"},
			"type": "adjv"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//V()",
			"tokenizer": {
				"name": "content"},
			"type": "verb"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//M()",
			"tokenizer": {
				"name": "content"},
			"type": "modal"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//N()",
			"tokenizer": {
				"name": "content"},
			"type": "noun"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//E()",
			"tokenizer": {
				"name": "content"},
			"type": "entity"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//U()",
			"tokenizer": {
				"name": "content"},
			"type": "url"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//R()",
			"tokenizer": {
				"name": "content"},
			"type": "pron"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//W()",
			"tokenizer": {
				"name": "content"},
			"type": "wdet"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//T()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//P()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//C()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//X()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//A()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//V()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//M()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//N()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//E()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//U()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//R()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//W()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//heading()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//tabtitle()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//head()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//cell()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//citation()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//ref()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//list()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//text()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//attr()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//pagelink()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//weblink()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//entity()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//quot()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//math()",
			"tokenizer": {
				"name": "word"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//char()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//code()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//bibref()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"},
		{
			"normalizer": [
				{
					"name": "orig"}],
			"select": "//time()",
			"tokenizer": {
				"name": "content"},
			"type": "orig"}],
	"searchindex": [
		{
			"normalizer": [
				{
					"name": "lc"},
				{
					"name": "entityid"}],
			"select": "//weblink@id",
			"tokenizer": {
				"expression": "^[a-z]{3,5}[:][/][/]([^ ?/]{1,32})",
				"index": 0,
				"name": "regex"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"},
				{
					"name": "entityid"}],
			"select": "//weblink@id",
			"tokenizer": {
				"expression": "^([a-z\\.]{6,24}[^ ?/]{1,20})",
				"index": 0,
				"name": "regex"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"},
				{
					"name": "entityid"}],
			"select": "//bibref()",
			"tokenizer": {
				"name": "content"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//category@cid",
			"tokenizer": {
				"name": "content"},
			"type": "categoryid"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//title@id",
			"tokenizer": {
				"name": "content"},
			"type": "headid"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//heading@id",
			"tokenizer": {
				"name": "content"},
			"type": "headid"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "/doc/title()",
			"tokenizer": {
				"name": "word"},
			"type": "title"},
		{
			"normalizer": [
				{
					"name": "lc"},
				{
					"name": "entityid"}],
			"options": {
				"position": "succ"},
			"select": "//N@id",
			"tokenizer": {
				"name": "content"},
			"type": "entity"},
		{
			"normalizer": [
				{
					"name": "lc"},
				{
					"name": "entityid"}],
			"options": {
				"position": "succ"},
			"select": "//E@id",
			"tokenizer": {
				"name": "content"},
			"type": "entity"},
		{
			"normalizer": [
				{
					"name": "lc"},
				{
					"name": "entityid"}],
			"options": {
				"position": "succ"},
			"select": "//R@id",
			"tokenizer": {
				"name": "content"},
			"type": "entity"},
		{
			"normalizer": [
				{
					"name": "lc"},
				{
					"name": "entityid"}],
			"select": "//E()",
			"tokenizer": {
				"name": "content"},
			"type": "entity"},
		{
			"normalizer": [
				{
					"name": "empty"}],
			"select": "//T",
			"tokenizer": {
				"name": "content"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "empty"}],
			"select": "//P",
			"tokenizer": {
				"name": "content"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//C()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//X()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//A()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//V()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//M()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"},
				{
					"name": "entityid"}],
			"options": {
				"position": "succ"},
			"select": "//N()",
			"tokenizer": {
				"name": "content"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"},
				{
					"name": "entityid"}],
			"options": {
				"position": "succ"},
			"select": "//E()",
			"tokenizer": {
				"name": "content"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//N()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//E()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//U()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//R()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//W()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//heading()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//tabtitle()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//head()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//cell()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//citation()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//ref()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//list()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//text()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//attr()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//pagelink()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//weblink()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//entity()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//quot()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//math()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//char()",
			"tokenizer": {
				"name": "word"},
			"type": "word"},
		{
			"normalizer": [
				{
					"name": "lc"}],
			"select": "//code()",
			"tokenizer": {
				"name": "word"},
			"type": "word"}],
	"segmenter": {
		"name": "textwolf"}}
}
{
"query": {
	"feature": [
		{
			"content": [
				{
					"type": "word",
					"value": "david"},
				{
					"type": "word",
					"value": "bowie"},
				{
					"type": "entity",
					"value": "david_bowie"}],
			"set": "search"}]}
}
{
"query": {
	"feature": [
		{
			"content": [
				{
					"type": "word",
					"value": "DAVID"},
				{
					"type": "word",
					"value": "BOWIE"}],
			"set": "search"}]}
}
