{
"qryeval": {
  "selection_sets": [
    "search"],
  "summarizers": [
    {
      "function": "attribute",
      "param": {
        "attribute": "title"}},
    {
      "function": "metadata",
      "param": {
        "name": "index"}}],
  "weighting": [
    {
      "feature": {
        "match": "search"},
      "function": "bm25",
      "param": {
        "avgdoclen": 1000,
        "b": "0.75",
        "k1": "1.2",
        "metadata_doclen": "doclen"}}],
  "weighting_sets": [
    "search"]}}
{
"queryresult": {
  "evalpass": 0,
  "nofranked": 3,
  "nofvisited": 5,
  "ranks": [
    {
      "field": {
        "end": 0,
        "start": 0},
      "summary": [
        {
          "name": "title",
          "value": "List of songs recorded by David Bowie"},
        {
          "name": "index",
          "value": 10}],
      "weight": "0.460034"},
    {
      "field": {
        "end": 0,
        "start": 0},
      "summary": [
        {
          "name": "title",
          "value": "Let's Dance (David Bowie album)"},
        {
          "name": "index",
          "value": 7}],
      "weight": "0.241621"},
    {
      "field": {
        "end": 0,
        "start": 0},
      "summary": [
        {
          "name": "title",
          "value": "David Bowie"},
        {
          "name": "index",
          "value": 6}],
      "weight": "0.199666"}]}}
{
"queryresult": {
  "evalpass": 0,
  "nofranked": 3,
  "nofvisited": 5,
  "ranks": [
    {
      "field": {
        "end": 0,
        "start": 0},
      "summary": [
        {
          "name": "title",
          "value": "List of songs recorded by David Bowie"},
        {
          "name": "index",
          "value": 10}],
      "weight": "0.460034"},
    {
      "field": {
        "end": 0,
        "start": 0},
      "summary": [
        {
          "name": "title",
          "value": "Let's Dance (David Bowie album)"},
        {
          "name": "index",
          "value": 7}],
      "weight": "0.241621"},
    {
      "field": {
        "end": 0,
        "start": 0},
      "summary": [
        {
          "name": "title",
          "value": "David Bowie"},
        {
          "name": "index",
          "value": 6}],
      "weight": "0.199666"}]}}
