{
"qryeval": {
  "selection_sets": [
    "search"],
  "summarizers": [
    {
      "function": "attribute",
      "param": {
        "attribute": "title"}}],
  "weighting": [
    {
      "feature": {
        "match": "search"},
      "function": "bm25",
      "param": {
        "avgdoclen": 1000,
        "b": "0.75",
        "k1": "1.2",
        "metadata_doclen": "doclen"}}],
  "weighting_sets": [
    "search"]}}
{
"queryresult": {
  "evalpass": 0,
  "nofranked": 5,
  "nofvisited": 5,
  "ranks": [
    {
      "field": {
        "end": 0,
        "start": 0},
      "summary": [
        {
          "name": "title",
          "value": "Tonight (David Bowie album)"}],
      "weight": "0.669520"},
    {
      "field": {
        "end": 0,
        "start": 0},
      "summary": [
        {
          "name": "title",
          "value": "VH1 Storytellers (David Bowie album)"}],
      "weight": "0.494061"},
    {
      "field": {
        "end": 0,
        "start": 0},
      "summary": [
        {
          "name": "title",
          "value": "List of songs recorded by David Bowie"}],
      "weight": "0.460034"},
    {
      "field": {
        "end": 0,
        "start": 0},
      "summary": [
        {
          "name": "title",
          "value": "Let's Dance (David Bowie album)"}],
      "weight": "0.241621"},
    {
      "field": {
        "end": 0,
        "start": 0},
      "summary": [
        {
          "name": "title",
          "value": "David Bowie"}],
      "weight": "0.199666"}]}}
{
"queryresult": {
  "evalpass": 0,
  "nofranked": 5,
  "nofvisited": 5,
  "ranks": [
    {
      "field": {
        "end": 0,
        "start": 0},
      "summary": [
        {
          "name": "title",
          "value": "Tonight (David Bowie album)"}],
      "weight": "0.669520"},
    {
      "field": {
        "end": 0,
        "start": 0},
      "summary": [
        {
          "name": "title",
          "value": "VH1 Storytellers (David Bowie album)"}],
      "weight": "0.494061"},
    {
      "field": {
        "end": 0,
        "start": 0},
      "summary": [
        {
          "name": "title",
          "value": "List of songs recorded by David Bowie"}],
      "weight": "0.460034"},
    {
      "field": {
        "end": 0,
        "start": 0},
      "summary": [
        {
          "name": "title",
          "value": "Let's Dance (David Bowie album)"}],
      "weight": "0.241621"},
    {
      "field": {
        "end": 0,
        "start": 0},
      "summary": [
        {
          "name": "title",
          "value": "David Bowie"}],
      "weight": "0.199666"}]}}
