{
"query":{
"sentence":[
	{
		"field": "text",
		"content": "David Bowie; Brian Eno; album",
		"results": "4",
		"minweight": "0.9",
		"analyzed":[
			{
				"term":{
					"type": "E",
					"value": "david_bowie"}},
			{
				"term":{
					"type": "E",
					"value": "brian_eno"}},
			{
				"expression":{
					"op": "union",
					"arg":[
						{
							"type": "N",
							"value": "album"},
						{
							"type": "N",
							"value": "debut_album"},
						{
							"type": "N",
							"value": "albums"},
						{
							"type": "N",
							"value": "song"},
						{
							"type": "N",
							"value": "songs"},
						{
							"type": "N",
							"value": "single"},
						{
							"type": "N",
							"value": "studio_album"},
						{
							"type": "N",
							"value": "label"},
						{
							"type": "N",
							"value": "ep"},
						{
							"type": "N",
							"value": "band"},
						{
							"type": "N",
							"value": "recording"}]}}]}]}}
