{
"query":{
"feature":[
	{
		"sentence":{
			"field": "text",
			"content": "David Bowie; Brian Eno; album",
			"results": "4",
			"minweight": "0.9"},
		"set": "search",
		"analyzed":[
			{
				"term":{
					"type": "E",
					"value": "david_bowie"}},
			{
				"term":{
					"type": "E",
					"value": "brian_eno"}},
			{
				"expression":{
					"op": "union",
					"arg":[
						{
							"term":{
								"type": "N",
								"value": "album"}},
						{
							"term":{
								"type": "N",
								"value": "solo_album"}},
						{
							"term":{
								"type": "N",
								"value": "albums"}},
						{
							"term":{
								"type": "N",
								"value": "debut_album"}},
						{
							"term":{
								"type": "N",
								"value": "recording"}},
						{
							"term":{
								"type": "N",
								"value": "title_track"}},
						{
							"term":{
								"type": "N",
								"value": "song"}},
						{
							"term":{
								"type": "N",
								"value": "compilation_album"}},
						{
							"term":{
								"type": "N",
								"value": "ep"}},
						{
							"term":{
								"type": "N",
								"value": "band"}}]}}]}]}}
{
"queryresult":{
"ranklist":{
	"evalpass": 0,
	"nofranked": 18,
	"nofvisited": 18,
	"ranks":[
		{
			"weight": "0.337903",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "List of songs recorded by David Bowie"}]},
		{
			"weight": "0.248799",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "\"Heroes\" (David Bowie album)"}]},
		{
			"weight": "0.242601",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "Beauty and the Beast (David Bowie song)"}]},
		{
			"weight": "0.208865",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "Outside (David Bowie album)"}]},
		{
			"weight": "0.176369",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "David Bowie (box set)"}]},
		{
			"weight": "0.113217",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "Stage (David Bowie album)"}]},
		{
			"weight": "0.028825",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "David Bowie"}]},
		{
			"weight": "0.000041",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "Let's Dance (David Bowie album)"}]},
		{
			"weight": "0.000041",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "David Bowie (1967 album)"}]},
		{
			"weight": "0.000040",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "Tonight (David Bowie album)"}]},
		{
			"weight": "0.000040",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "Without You (David Bowie song)"}]},
		{
			"weight": "0.000040",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "Soul Love (David Bowie song)"}]},
		{
			"weight": "0.000040",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "Changes (David Bowie song)"}]},
		{
			"weight": "0.000040",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "VH1 Storytellers (David Bowie album)"}]},
		{
			"weight": "0.000039",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "Never Let Me Down (David Bowie song)"}]},
		{
			"weight": "0.000039",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "Liza Jane (David Bowie song)"}]},
		{
			"weight": "0.000039",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "List of awards and nominations received by David Bowie"}]},
		{
			"weight": "0.000029",
			"field":{
				"start": 0,
				"end": 0},
			"summary":[
				{
					"name": "title",
					"value": "List of David Bowie concert tours"}]}]}}}
