set( Boost_USE_MULTITHREADED ON)
set( Boost_INCLUDE_DIR /usr/include )
find_package( Boost 1.53.0 COMPONENTS atomic QUIET )
if( Boost_ATOMIC_FOUND )
	if( WITH_PYTHON STREQUAL "YES" )
		find_package( Boost 1.53.0 REQUIRED COMPONENTS thread system date_time atomic python )
	else( WITH_PYTHON STREQUAL "YES" )
		find_package( Boost 1.53.0 REQUIRED COMPONENTS thread system date_time atomic )
	endif( WITH_PYTHON STREQUAL "YES" )
else()
	if( WITH_PYTHON STREQUAL "YES" )
		find_package( Boost 1.53.0 REQUIRED COMPONENTS thread system date_time python )
	else( WITH_PYTHON STREQUAL "YES" )
		find_package( Boost 1.53.0 REQUIRED COMPONENTS thread system date_time )
	endif( WITH_PYTHON STREQUAL "YES" )
endif()
