comment --
template main ENDHTML {{ }}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<title>Strus Lua interface documentation</title>
	<link rel="stylesheet" href="ldoc.css" type="text/css" />
</head>
<body>
<div class="container">
<div class="product">
	<div class="product_logo"> <img class="product_logo_img" src="images/logotype.jpg" alt="Strus"/></div>
	<div class="product_name">{{project}} Lua Bindings</div>
	<div class="product_release">{{release}}</div>
	<div class="product_author">{{author}}</div>
	<div class="product_copyright">{{copyright}}</div>
	<div class="product_license">{{license}}</div>
	<div class="product_description">Lua interface for strus, a set of libraries and programs to build a text search engine</div>
</div> <!-- product -->
<!-- Menu -->
<div class="navigation">
<h1>strus</h1>

<h2>Classes</h2>
<div class="navclass">
	{{classnav}}
</div>
</div> <!-- navigation -->

<div class="content">
<h2>Classes</h2>
<div class="classlist">
	{{classlist}}
</div>
</div> <!-- content -->

<h2>Interface description</h2>
<div class="classinterface">
	{{classinterface}}
</div>

<div class="about">
<i>generated by papugaDoc ({{project}} {{release}})</i>
</div>

</div>
</body>
</html>
ENDHTML

variable project
variable author
variable copyright
variable license
variable release

template classnav=class END {{ }}
<div class="classname">{{classname}}</div>
END

template classlist=class END {{ }}
<div class="class"><div class="classname">{{classname}}</div>
<div class="classdescr">{{description}}</div></div>
END

template classinterface=class END {{ }}
<h2>{{classname}}</h2>
{{constructortable}}
{{methodtable}}
END

template constructortable=class END {{ }}
<h3>Constructor</h3>
{{constructorlist}}
END

template methodtable=class END {{ }}
<h3>Methods</h3>
{{methodlist}}
END

group method constructor
template constructorlist=constructor END {{ }}
<div class="constructor">
<div class="name">{{constructorname}}</div>
<div class="description">{{description}}</div>
<div class="parameterlist">{{parameterlist}}</div>
<div class="examples">{{call_examples}}</div>
</div>
END

template methodlist=method END {{ }}
<div class="method">
<div class="name">{{methodname}}</div>
<div class="description">{{description}}</div>
<div class="parameterlist">{{parameterlist}}</div>
<div class="examples">{{call_examples}}</div>
</div>
END

template parameterlist=param END {{ }}
<div class="param">
<div class="paramname">{{paramname}}</div>
<div class="paramdescr">{{paramdescr}}</div>
<div class="paramexamples">{{value_examples}}</div>
</div>
END

template call_examples=usage END {{ }}
<div class="example">{{example}}</div>
END

template value_examples=usage END {{ }}
<div class="example">{{example}}</div>
END

variable constructorname=constructor
variable methodname=method
variable classname=class
variable description=brief
variable paramname=param[0]
variable paramdescr=param[1:] xmlencode
variable example=usage xmlencode
