template main ENDHTML {{ }}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<head>
	<title>Strus Lua interface documentation</title>
	<link rel="stylesheet" href="luadoc.css" type="text/css" />
</head>
<body>
<div id="container">
<div id="product">
	<div id="product_logo">images/logotype.jpg</div>
	<div id="product_name">Strus</div>
	<div id="product_description">Lua interface for strus, a set of libraries and programs to build a text search engine</div>
</div>
<div id="main">
<!-- Menu -->
<div id="navigation">
<br/>
<h1>strus</h1>

<h2>Classes</h2>
<ul>
	{{navclasslist}}
</ul>
</div>

<div id="content">
<h2>Modules</h2>
<table class="module_list">
	{{classlist}}
</table>

</div>
</div>
<div id="about">
<i>generated by papugaDoc (papuga 0.0.0) with the template strusLuaDoc.tpl</a></i>
</div>
</div>
</body>
</html>
ENDHTML
template navclasslist=class END {{ }}
<li><div id="navclass">{{classname}}</div></li>
END
template classlist=class END {{ }}
<li><div id="class"><div id="classname">{{classname}}</div><div id="classdescr">{{classdescr}}</div></div></li>
END
variable classname=class
variable classdescr=brief
