comment --
template main ENDHTML {{ }}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<title>Strus Lua interface documentation</title>
	<link rel="stylesheet" href="ldoc.css" type="text/css" />
</head>
<body>
<script type="text/javascript">
function showClassNav( name) {
	var navclassid = 'navclass_' + name;
	var navmemberlistid = 'navmemberlist_' + name;
	var allElements = document.getElementsByTagName("*");
	for(var i=0; i < allElements.length; i++)
	{
		if (allElements[i].className === "navclass")
		{
			if (allElements[i].id === navclassid) {
				allElements[i].style.background = "#66ff33";
				allElements[i].style.display = 'block';
			}
			else
			{
				allElements[i].style.background = "#ecffe6";
			}
		}
		else if (allElements[i].className === "navmemberlist")
		{
			if (allElements[i].id === navmemberlistid) {
				allElements[i].style.background = "#66ff33";
				allElements[i].style.display = 'block';
			} else {
				allElements[i].style.background = "#ecffe6";
				allElements[i].style.display = 'none';
			}
		}
	}
	var title = document.getElementById( "nav_title_methods");
	title.style.display = 'block';
}

function showMethod( name) {
	var navmemberid = 'navmember_' + name;
	var memberid = 'member_' + name;
	var allElements = document.getElementsByTagName("*");
	for(var i=0; i < allElements.length; i++)
	{
		if (allElements[i].className === "navmethod"
		||  allElements[i].className === "navconstructor")
		{
			if (allElements[i].id === navmemberid) {
				allElements[i].style.background = "#66ff33";
				allElements[i].style.display = 'block';
			}
			else
			{
				allElements[i].style.background = "#ecffe6";
			}
		}
		else if (allElements[i].className === "method"
		|| allElements[i].className === "constructor")
		{
			if (allElements[i].id === memberid) {
				allElements[i].style.background = "#66ff33";
				allElements[i].style.display = 'block';
			} else {
				allElements[i].style.background = "#ecffe6";
				allElements[i].style.display = 'none';
			}
		}
	}
	var title = document.getElementById( "nav_title_methods");
	title.style.display = 'block';
}
</script>

<div class="container">
<div class="product">
	<div class="product_logo"> <img class="product_logo_img" src="images/logotype.jpg" alt="Strus"/></div>
	<div class="product_name">{{project}} Lua Bindings</div>
	<div class="product_release">{{release}}</div>
	<div class="product_author">{{author}}</div>
	<div class="product_copyright">{{copyright}}</div>
	<div class="product_license">{{license}}</div>
	<div class="product_description">Lua interface for strus, a set of libraries and programs to build a text search engine</div>
</div> <!-- product -->
<!-- Menu -->
<div class="navigation">
<h1>strus</h1>

<h2 id="nav_title_classes">Classes</h2>
<div class="navclasslist">
	{{navclasslist}}
</div>
<h2 id="nav_title_methods">Classes</h2>
{{navmemberlist}}
</div> <!-- navigation -->

<div class="content">
<h2>Classes</h2>
<div class="classlist">
	{{classlist}}
</div>
</div> <!-- content -->

<h2 id="title_method">Method interface description</h2>
<div class="classinterface">
	{{classinterface}}
</div>

<div class="about">
<i>generated by papugaDoc ({{project}} {{release}})</i>
</div>

</div>
</body>
</html>
ENDHTML

variable project
variable author
variable copyright
variable license
variable release

namespace classname=class
template navclasslist=class END {{ }}
<div class="navclass" id="navclass_{{classname}}" onclick="showClassNav('{{classname}}');">{{classname}}</div>
END

template classlist=class END {{ }}
<div class="class"><div class="classname">{{classname}}</div>
<div class="classdescr">{{description}}</div></div>
END

template navmemberlist=class END {{ }}
<div class="navmemberlist" id="navmemberlist_{{classname}}">
	{{navmember}}
</div>
END

template navmember=method END {{ }}
<div class="navmethod" id="navmember_{{classname}}_{{methodname}}" onclick="showMethod('{{classname}}_{{methodname}}')">{{methodname}}</div>
END
template navmember=constructor END {{ }}
<div class="navconstructor"id="navmember_{{classname}}_{{methodname}}" onclick="showMethod('navmember_{{classname}}_{{methodname}}')>{{constructorname}}</div>
END

template classinterface=class END {{ }}
<h2>{{classname}}</h2>
{{constructortable}}
{{methodtable}}
END

template constructortable=class END {{ }}
<h3>Constructor</h3>
{{constructorlist}}
END

template methodtable=class END {{ }}
<h3>Methods</h3>
{{methodlist}}
END

group method constructor
template constructorlist=constructor END {{ }}
<div class="constructor" id='member_{{classname}}_{{constructorname}}'>
<div class="name">{{constructorname}}</div>
<div class="description">{{description}}</div>
<div class="parameterlist">{{parameterlist}}</div>
<div class="examples">{{call_examples}}</div>
</div>
END

template methodlist=method END {{ }}
<div class="method" id='member_{{classname}}_{{constructorname}}'>
<div class="name">{{methodname}}</div>
<div class="description">{{description}}</div>
<div class="parameterlist">{{parameterlist}}</div>
<div class="examples">{{call_examples}}</div>
</div>
END

template parameterlist=param END {{ }}
<div class="param">
<div class="paramname">{{paramname}}</div>
<div class="paramdescr">{{paramdescr}}</div>
<div class="paramexamples">{{value_examples}}</div>
</div>
END

template call_examples=usage END {{ }}
<div class="example">{{example}}</div>
END

template value_examples=usage END {{ }}
<div class="example">{{example}}</div>
END

variable constructorname=constructor
variable methodname=method
variable description=brief
variable paramname=param[0]
variable paramdescr=param[1:] xmlencode
variable example=usage xmlencode
